import { v4 as uuid } from 'uuid'

let inventory = [


  { categories: ['cabellos'], name: 'Multi-Peptide Serum for Hair Density', price: '800', image: 'https://theordinary.deciem.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dwa99641bd/Images/products/The%20Ordinary/rdn-multi-peptide-serum-for-hair-density-60ml.png?sw=900&sh=900&sm=fit', description: 'Un suero concentrado para cabello que se ve más grueso, denso, más lleno y más saludable.', brand: 'Jason Bourne', currentInventory: 28 , linkpago: "https://mpago.la/2Vt5arf"},
  { categories: ['cabellos'], name: 'Hydration Support', price: '800', image: 'https://hif.deciem.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw8846a76a/Images/products/Hif/hif-hydration-support-180ml.png?sw=900&sh=900&sm=fit', description: 'Con HA de bajo peso molecular', brand: 'Jason Bourne', currentInventory: 28 , linkpago: "https://mpago.la/2Vt5arf"},
  { categories: ['cabellos'], name: 'SupportVolume Support ', price: '800', image: 'https://hif.deciem.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dwc547ea3e/Images/products/Hif/hif-volume-support-180ml.png?sw=900&sh=900&sm=fit', description: 'With pea bio-peptides', brand: 'Jason Bourne', currentInventory: 28 , linkpago: "https://mpago.la/2Vt5arf"},

  
  
  { categories: ['piel'], name: 'Niodcatalizador de elasticidad del cuello (nec) 4.2', price: '1200', image: 'https://ydalimir-ecommerce.s3.amazonaws.com/pp1_ac9a396d60.png', description: 'Estas tecnologías ayudan a reducir la apariencia de piel flácida que generalmente es causada por la enzima clave que descompone la elastina (o elastasa) y la progerina, una proteína truncada que causa un envejecimiento celular disfuncional. (Tenga en cuenta que la elastina es "buena" y la elastasa es "mala" y algunos artículos escriben mal o, peor aún, confunden estos dos componentes entre sí). ', brand: 'Jason Bourne', currentInventory: 17 , linkpago: "https://buy.stripe.com/test_14kcQg6xV0Lb8FycMO"},
  { categories: ['piel'], name: 'Hand Chemistry', price: '1600', image: 'https://chemistrybrand.deciem.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dwb17a2f53/Images/products/The%20Chemistry%20Brand/tcb-hand-chemistry-30ml.png?sw=900&sh=900&sm=fit', description: 'Cuidado de la piel pro-Repair para manos', brand: 'Jason Bourne', currentInventory: 28, linkpago: "https://buy.stripe.com/test_9AQ8A0cWj0Lbg80eUU" },
  { categories: ['piel'], name: 'Hyaluronic Concentrate', price: '800', image: 'https://chemistrybrand.deciem.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw49467211/Images/products/The%20Chemistry%20Brand/tcb-hyaluronic-concentrate-240ml.png?sw=900&sh=900&sm=fit', description: 'A big tub of Hyaluronic acid', brand: 'Jason Bourne', currentInventory: 44 , linkpago: "https://mpago.la/2Vt5arf"},
  { categories: ['piel'], name: 'Next Natural Moisturizing Factors + HA', price: '1200', image: 'https://theordinary.deciem.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw2ff47ee4/Images/products/The%20Ordinary/rdn-natural-moisturizing-factors-ha-30ml.png?sw=800&sh=800&sm=fit', description: 'Surface hydration formula', brand: 'Jason Bourne', currentInventory: 17 , linkpago: "https://buy.stripe.com/test_9AQ8A0cWj0Lbg80eUU"},
  { categories: ['piel'], name: 'Hyaluronic Acid 2% + B5', price: '1600', image: 'https://theordinary.deciem.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw6f82b69b/Images/products/The%20Ordinary/rdn-squalane-cleanser-50ml.png?sw=800&sh=800&sm=fit', description: 'A hydration support formula with ultra-pure, vegan hyaluronic acid', brand: 'Jason Bourne', currentInventory: 28, linkpago: "https://buy.stripe.com/test_9AQ8A0cWj0Lbg80eUU" },
  
  
  { categories: ['cuerpo'], name: 'Retin-Oil', price: '1200', image: 'https://chemistrybrand.deciem.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw493907ca/Images/products/The%20Chemistry%20Brand/tcb-retin-oil-100ml.png?sw=900&sh=900&sm=fit', description: 'Estas tecnologías ayudan a reducir la apariencia de piel flácida que generalmente es causada por la enzima clave que descompone la elastina (o elastasa) y la progerina, una proteína truncada que causa un envejecimiento celular disfuncional. (Tenga en cuenta que la elastina es "buena" y la elastasa es "mala" y algunos artículos escriben mal o, peor aún, confunden estos dos componentes entre sí).', brand: 'Jason Bourne', currentInventory: 17 , linkpago: "https://buy.stripe.com/test_9AQ8A0cWj0Lbg80eUU"},
  { categories: ['cuerpo'], name: 'Hand Chemistry', price: '1600', image: 'https://chemistrybrand.deciem.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dwb17a2f53/Images/products/The%20Chemistry%20Brand/tcb-hand-chemistry-30ml.png?sw=900&sh=900&sm=fit', description: 'Cuidado de la piel pro-Repair para manos', brand: 'Jason Bourne', currentInventory: 28, linkpago: "https://buy.stripe.com/test_9AQ8A0cWj0Lbg80eUU" },
  { categories: ['cuerpo'], name: 'Hyaluronic Concentrate', price: '800', image: 'https://chemistrybrand.deciem.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw49467211/Images/products/The%20Chemistry%20Brand/tcb-hyaluronic-concentrate-240ml.png?sw=900&sh=900&sm=fit', description: 'A big tub of Hyaluronic acid', brand: 'Jason Bourne', currentInventory: 44 , linkpago: "https://mpago.la/2Vt5arf"},
  { categories: ['cabello'], name: 'Next Natural Moisturizing Factors + HA', price: '1200', image: 'https://theordinary.deciem.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw2ff47ee4/Images/products/The%20Ordinary/rdn-natural-moisturizing-factors-ha-30ml.png?sw=800&sh=800&sm=fit', description: 'Surface hydration formula', brand: 'Jason Bourne', currentInventory: 17 , linkpago: "https://buy.stripe.com/test_9AQ8A0cWj0Lbg80eUU"},
  { categories: ['cabello'], name: 'Hyaluronic Acid 2% + B5', price: '1600', image: 'https://theordinary.deciem.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw6f82b69b/Images/products/The%20Ordinary/rdn-squalane-cleanser-50ml.png?sw=800&sh=800&sm=fit', description: 'A hydration support formula with ultra-pure, vegan hyaluronic acid', brand: 'Jason Bourne', currentInventory: 28, linkpago: "https://buy.stripe.com/test_9AQ8A0cWj0Lbg80eUU" },
  
 { categories: ['cabello'], name: 'Next Natural Moisturizing Factors + HA', price: '1200', image: 'https://theordinary.deciem.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw2ff47ee4/Images/products/The%20Ordinary/rdn-natural-moisturizing-factors-ha-30ml.png?sw=800&sh=800&sm=fit', description: 'Surface hydration formula', brand: 'Jason Bourne', currentInventory: 17 , linkpago: "https://buy.stripe.com/test_9AQ8A0cWj0Lbg80eUU"},
  { categories: ['cabello'], name: 'Hyaluronic Acid 2% + B5', price: '1600', image: 'https://theordinary.deciem.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw6f82b69b/Images/products/The%20Ordinary/rdn-squalane-cleanser-50ml.png?sw=800&sh=800&sm=fit', description: 'A hydration support formula with ultra-pure, vegan hyaluronic acid', brand: 'Jason Bourne', currentInventory: 28, linkpago: "https://buy.stripe.com/test_9AQ8A0cWj0Lbg80eUU" },
  { categories: ['cabello'], name: 'AHA 30% + BHA 2% Peeling Solution', price: '550', image: 'https://theordinary.deciem.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw698fd41b/Images/products/The%20Ordinary/rdn-aha-30pct-bha-2pct-peeling-solution-30ml.png?sw=800&sh=800&sm=fit', description: 'You don’t have to go outside to be rugged. The Cigar rawhide sofa features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather sofa is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.', brand: 'Jason Bourne', currentInventory: 31 },
  { categories: ['cabello'], name: 'Next Niacinamide 10% + ZincS 1%', price: '800', image: 'https://theordinary.deciem.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw698fd41b/Images/products/The%20Ordinary/rdn-aha-30pct-bha-2pct-peeling-solution-30ml.png?sw=800&sh=800&sm=fit', description: 'High-strength vitamin and mineral blemish formula', brand: 'Jason Bourne', currentInventory: 44 , linkpago: "https://mpago.la/2Vt5arf"},
  { categories: ['makeup'], name: 'Next Niacinamide 10% + Zinc 1%', price: '800', image: 'https://theordinary.deciem.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dwa53d85c0/Images/products/The%20Ordinary/rdn-niacinamide-10pct-zinc-1pct-30ml.png?sw=800&sh=800&sm=fit', description: 'High-strength vitamin and mineral blemish formula', brand: 'Jason Bourne', currentInventory: 44, linkpago: "https://buy.stripe.com/test_9AQ8A0cWj0Lbg80eUU" },
  { categories: ['makeup'], name: 'Next Natural Moisturizing Factors + HA', price: '1200', image: 'https://theordinary.deciem.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw2ff47ee4/Images/products/The%20Ordinary/rdn-natural-moisturizing-factors-ha-30ml.png?sw=800&sh=800&sm=fit', description: 'Surface hydration formula', brand: 'Jason Bourne', currentInventory: 17, linkpago: "https://buy.stripe.com/test_9AQ8A0cWj0Lbg80eUU" },
  { categories: ['makeup'], name: 'Hyaluronic Acid 2% + B5', price: '1600', image: 'https://theordinary.deciem.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw6f82b69b/Images/products/The%20Ordinary/rdn-squalane-cleanser-50ml.png?sw=800&sh=800&sm=fit', description: 'A hydration support formula with ultra-pure, vegan hyaluronic acid', brand: 'Jason Bourne', currentInventory: 28 , linkpago: "https://buy.stripe.com/test_9AQ8A0cWj0Lbg80eUU"},
  { categories: ['makeup'], name: 'AHA 30% + BHA 2% Peeling Solution', price: '550', image: 'https://theordinary.deciem.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw698fd41b/Images/products/The%20Ordinary/rdn-aha-30pct-bha-2pct-peeling-solution-30ml.png?sw=800&sh=800&sm=fit', description: 'You don’t have to go outside to be rugged. The Cigar rawhide sofa features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather sofa is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.', brand: 'Jason Bourne', currentInventory: 31 , linkpago: "https://buy.stripe.com/test_9AQ8A0cWj0Lbg80eUU" },  
  { categories: ['makeup'], name: 'Next Niacinamide 10% + Zinc 1%', price: '800', image: 'https://theordinary.deciem.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dwa53d85c0/Images/products/The%20Ordinary/rdn-niacinamide-10pct-zinc-1pct-30ml.png?sw=800&sh=800&sm=fit', description: 'High-strength vitamin and mineral blemish formula', brand: 'Jason Bourne', currentInventory: 44, linkpago: "https://buy.stripe.com/test_9AQ8A0cWj0Lbg80eUU" },
  { categories: ['makeup'], name: 'Next Natural Moisturizing Factors + HA', price: '1200', image: 'https://theordinary.deciem.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw2ff47ee4/Images/products/The%20Ordinary/rdn-natural-moisturizing-factors-ha-30ml.png?sw=800&sh=800&sm=fit', description: 'Surface hydration formula', brand: 'Jason Bourne', currentInventory: 17, linkpago: "https://buy.stripe.com/test_9AQ8A0cWj0Lbg80eUU" },
  { categories: ['makeup'], name: 'Hyaluronic Acid 2% + B5', price: '1600', image: 'https://theordinary.deciem.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw6f82b69b/Images/products/The%20Ordinary/rdn-squalane-cleanser-50ml.png?sw=800&sh=800&sm=fit', description: 'A hydration support formula with ultra-pure, vegan hyaluronic acid', brand: 'Jason Bourne', currentInventory: 28 , linkpago: "https://buy.stripe.com/test_9AQ8A0cWj0Lbg80eUU"},
  { categories: ['makeup'], name: 'AHA 30% + BHA 2% Peeling Solution', price: '550', image: 'https://theordinary.deciem.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw698fd41b/Images/products/The%20Ordinary/rdn-aha-30pct-bha-2pct-peeling-solution-30ml.png?sw=800&sh=800&sm=fit', description: 'You don’t have to go outside to be rugged. The Cigar rawhide sofa features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather sofa is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.', brand: 'Jason Bourne', currentInventory: 31, linkpago: "https://buy.stripe.com/test_9AQ8A0cWj0Lbg80eUU" }, 

  { categories: ['cuidados'], name: 'Next Niacinamide 10% + Zinc 1%', price: '800', image: 'https://theordinary.deciem.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dwa53d85c0/Images/products/The%20Ordinary/rdn-niacinamide-10pct-zinc-1pct-30ml.png?sw=800&sh=800&sm=fit', description: 'High-strength vitamin and mineral blemish formula', brand: 'Jason Bourne', currentInventory: 44, linkpago: "https://buy.stripe.com/test_9AQ8A0cWj0Lbg80eUU" },
  { categories: ['cuidados'], name: 'Next Natural Moisturizing Factors + HA', price: '1200', image: 'https://theordinary.deciem.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw2ff47ee4/Images/products/The%20Ordinary/rdn-natural-moisturizing-factors-ha-30ml.png?sw=800&sh=800&sm=fit', description: 'Surface hydration formula', brand: 'Jason Bourne', currentInventory: 17, linkpago: "https://buy.stripe.com/test_9AQ8A0cWj0Lbg80eUU" },
  
  
  // { 
]

inventory.map(i => {
  i.id = uuid()
  return i
})

export default inventory